# Copyright (c) 2024 Graham R King
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice (including the
# next paragraph) shall be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
from __future__ import annotations

import textwrap
from copy import deepcopy


class TypeHinter:
    INDENT_UNITS = 1

    HEADERS = (
        "# DO NOT EDIT this file, it is automatically generated.",
        "# ",
        "# This file is only used as a code completion helper",
        "# for editors, it is not used at runtime.",
        "from __future__ import annotations",
        "from typing import TypeAlias, Annotated",
        "from enum import Enum, IntFlag",
        "new_id: TypeAlias = int",
        "fd: TypeAlias = int",
        "",
    )

    def create_type_hinting(self, structure: dict, path: str) -> None:
        file_name = f"{path}/__init__.pyi"
        headers = [line + "\n" for line in self.HEADERS]
        class_definitions = []

        for class_name, details in structure.items():
            class_declaration = self._create_class_declaration(class_name, details)
            class_body = self._create_class_body(class_name, details)
            class_definitions.append(class_declaration + class_body)

        with open(file_name, "w", encoding="utf-8") as outfile:
            outfile.writelines(headers + class_definitions)

    def _create_class_declaration(self, class_name: str, details: dict) -> str:
        declaration = f"class {class_name}:\n"
        declaration += self.indent(details["description"], 1, comment=True)
        declaration += self._pad("object_id = 0\n", 1)
        declaration += self._pad(f"version = {details['version']}\n\n", 1)
        return declaration

    def _create_class_body(self, class_name: str, details: dict) -> str:
        body = []
        body.append(self.process_enums(details.get("enums", [])))

        body.append(self.process_members(class_name, details.get("requests", [])))

        events = self.process_members(
            class_name, details.get("events", []), events=True
        )
        if events:
            body.append(self._pad("class events:\n" + events, 1))

        return "\n".join(body) + "\n"

    def process_members(
        self, class_name: str, members: list[dict], *, events: bool = False
    ) -> str:
        indent_level = 2 if events else 1

        definitions = []

        for member in members:
            new_args, return_type = self._process_args(
                class_name, member["args"], events
            )

            docstring = self._create_docstring(member, new_args, return_type)
            signature = [
                self._pad("@staticmethod", indent_level),
                self._pad(
                    f"def {member['name']}({', '.join(f'{arg["name"]}: {arg["type"]}' for arg in new_args)})"
                    f" -> {return_type or 'None'}:",
                    indent_level,
                ),
                self.indent(docstring, indent_level + 1),
                self._pad("...", indent_level + 1),
            ]

            definitions.append("\n".join(signature) + "\n")

        return "\n".join(definitions)

    def _process_args(
        self, class_name: str, args: list[dict], events: bool
    ) -> tuple[list[dict], str | None]:
        new_args = []
        return_type = None

        for arg in deepcopy(args):
            processed_return_type = self._process_single_arg(arg, class_name, events)
            if processed_return_type:
                return_type = processed_return_type
                continue
            new_args.append(arg)

        return new_args, return_type

    def _process_single_arg(
        self, arg: dict, class_name: str, events: bool
    ) -> str | None:
        if arg["type"] == "new_id":
            interface = arg.get("interface")
            if interface and not events:
                return interface
            if interface and events:
                arg["type"] = interface
        elif arg["type"] == "object" and arg.get("interface"):
            arg["type"] = arg["interface"]
        elif arg["type"] == "string":
            arg["type"] = "str"
        elif arg.get("enum"):
            enum_ref = arg["enum"]
            if "." in enum_ref:
                arg["type"] = enum_ref
            else:
                arg["type"] = f"{class_name}.{enum_ref}"
        return None

    def _create_docstring(
        self, member: dict, args: list[dict], return_type: str | None
    ) -> str:
        docstring_parts = []

        if member.get("description"):
            docstring_parts.append(member["description"])

        args_with_descriptions = [arg for arg in args if arg.get("description")]
        if args_with_descriptions:
            docstring_parts.append("")
            docstring_parts.append("Args:")
            for arg in args_with_descriptions:
                arg_desc = arg["description"].strip()
                if arg_desc:
                    docstring_parts.append(self._pad(f"{arg['name']}: {arg_desc}", 1))

        if return_type:
            docstring_parts.append("")
            docstring_parts.append("Returns:")
            docstring_parts.append(self._pad(f"{return_type}: The created object", 1))

        return "\n".join(docstring_parts) if docstring_parts else ""

    def process_enums(self, members: list[dict]) -> str:
        indent_level = 1

        definitions = []

        for member in members:
            enum_name = member["name"]
            enum_type = "IntFlag" if member.get("bitfield") else "Enum"

            signature = [self._pad(f"class {enum_name}({enum_type}):", indent_level)]
            for arg in member["args"]:
                value_name = arg["name"]
                try:
                    int(value_name)
                    value_name = f"{enum_name}_{value_name}"
                except ValueError:
                    pass
                signature.append(self._pad(f"{value_name}: int", indent_level + 1))

            definitions.append("\n".join(signature) + "\n\n")

        return "\n".join(definitions)

    @classmethod
    def _pad(cls, astring: str, amount: int):
        return (" " * (cls.INDENT_UNITS * amount)) + astring

    @classmethod
    def indent(
        cls, input_string: str, indent_level: int, *, comment: bool = True
    ) -> str:
        indent = cls._pad("", indent_level)
        if comment:
            input_string = f'"""\n{input_string}\n"""\n'

        return textwrap.indent(input_string, indent)
